trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  artifactVersion: ''

steps:
- checkout: self
  clean: true

- script: dotnet build
  displayName: 'Build the artifact'


- script: |
    major_version=1
    minor_version=0
    build_number=$(Build.BuildNumber)
    new_version="$major_version.$minor_version.$build_number"
    echo "New artifact version: $new_version"
    artifactVersion="$new_version"
  displayName: 'Increment Version (Bash)'

- script: dotnet pack -o $(Build.ArtifactStagingDirectory) --version $(Build.BuildNumber)
  displayName: 'Create NuGet Package'

- publish: $(Build.ArtifactStagingDirectory)/**/*.nupkg
  displayName: 'Publish NuGet Package'
  artifact: hello_world  # Replace with your feed name
  condition: always()
