pool:
  vmImage: ubuntu-latest
  name: default
  
stages:
- stage: build
  jobs:
  - job: pack_publish
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    
    steps:


    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarQube Localhost'
        scannerMode: 'MSBuild'
        projectKey: 'firstproj_firstproj_538b5c36-e25a-4d40-af2a-589005a19f5c'
    
    - script: dotnet pack -p Version=1.0.$(Build.BuildId)
      displayName: 'build the artifact'

    - script: dotnet nuget push --source "hello_world" --api-key az $(System.DefaultWorkingDirectory)/bin/Release/1.0.$(Build.BuildId).nupkg
      displayName: 'publish artifact'

    - task: SonarQubeAnalyze@5
    
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'

