trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  artifactVersion: '1.0.0'


steps:
- checkout: self
  clean: true

- script: dotnet build
  displayName: 'build the artifact'

- script: |  # Optional script for version manipulation (powershell@3)
    $majorVersion = "${env:MajorVersion}"
    $minorVersion = "${env:MinorVersion}"
    $buildNumber = $(Build.BuildNumber)
    $newVersion = "$majorVersion.$minorVersion.$buildNumber"
    Write-Host "New artifact version: $newVersion"
    $artifactVersion = $newVersion
  displayName: 'Increment Version (Optional)'

- publish: $(System.DefaultWorkingDirectory)/bin/Debug/net8.0/$(artifactVersion)/ConsoleApp1.dll
  artifact: helloworld
