trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  artifactVersion: ''

steps:
- checkout: self
  clean: true

- script: dotnet build
  displayName: 'Build the artifact'

- script: |
    major_version=1
    minor_version=0
    new_version="$major_version.$minor_version.$Build.BuildId"
    echo "New artifact version: $new_version"
    artifactVersion="$new_version"
  displayName: 'Increment Version (Bash)'

- script: dotnet pack -p Version=$artifactVersion
  displayName: 'Create NuGet Package'

- script: dotnet nuget push --source "hello_world" --api-key az /home/or/azure_devops/azure-test/bin/Release/ConsoleApp1.1.0.$Build.BuildId.nupkg
  displayName: 'publish NuGet Package'
