trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  artifactVersion: ''

steps:
- checkout: self
  clean: true

- script: |  # Combine setting version and potentially removing date
    major_version=1
    minor_version=0
    build_number=$(Build.BuildNumber)

    # Remove the date from the build number (assuming YYYYMMDD format, optional)
    build_number_without_date=${build_number:0:5}${build_number:7}  # Extract first 5 and last 2 digits

    # Use the desired version format (including build number)
    new_version="$major_version.$minor_version.$build_number"  # Use build_number_without_date if needed
    echo "New artifact version: $new_version"
    artifactVersion="$new_version"

    # Set NuGet version and build the project
    dotnet pack --configuration Release -p:ContinuousIntegrationBuild=true -p:Version=$new_version
  displayName: 'Set NuGet Version, Remove Date (Optional), and Build'

- script: dotnet nuget push --source "hello_world" --api-key az /home/or/azure-devops/azure-test/bin/Release/ConsoleApp1.$artifactVersion.nupkg
  displayName: 'publish NuGet Package'
