pool:
  vmImage: ubuntu-latest
  name: default
  
stages:
- stage: build
  jobs:
  - job: Build   
    steps:

    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarQube Localhost'
        scannerMode: 'MSBuild'
        projectKey: 'firstproj_firstproj_538b5c36-e25a-4d40-af2a-589005a19f5c'
    
    - script: nuget pack ConsoleApp1.nuspec -Version 1.0.$(Build.BuildId)
      displayName: 'build the artifact'

    - script: dotnet nuget push --source "hello_world_sq" --api-key az $(System.DefaultWorkingDirectory)/hello_world_sq.1.0.$(Build.BuildId).nupkg
      displayName: 'publish artifact'

    - task: SonarQubeAnalyze@5
    
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'



