# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  majorVersion: '1'
  minorVersion: '0'
  artifactVersion: ''

steps:
- checkout: self
  clean: true

- script: dotnet build
  displayName: 'Build the artifact'


- script: |
    major_version=${env:MajorVersion}
    minor_version=${env:MinorVersion}
    build_number=$(Build.BuildNumber)
    new_version="$major_version.$minor_version.$build_number"
    echo "New artifact version: $new_version"
    artifactVersion="$new_version"
  displayName: 'Increment Version (Bash)'

- publish: $(System.DefaultWorkingDirectory)/bin/Debug/net8.0/ConsoleApp1.dll
  artifact: helloworld
