# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  artifactVersion: '1.0.0'  # Initial version

steps:
- checkout: self
  clean: true

- script: dotnet build
  displayName: 'Build the artifact'

# Removed the optional PowerShell script (not compatible with bash)

- script: |  # Bash script for version manipulation
    major_version=${env:MajorVersion}  # Use lower case for variable names
    minor_version=${env:MinorVersion}
    build_number=$(Build.BuildNumber)  # Use $( ) for pre-defined variables
    new_version="$major_version.$minor_version.$build_number"
    echo "New artifact version: $new_version"
    artifactVersion="$new_version"
  displayName: 'Increment Version (Bash)'

- publish: $(System.DefaultWorkingDirectory)/bin/Debug/net8.0/ConsoleApp1.dll
  artifact: helloworld
